// <auto-generated />
namespace EducationPortalConsoleApp.Helpers
{
    using System;
    using EducationPortalConsoleApp.DependencyInjection;

    public static class ProviderServicePL
    {
        private static IServiceProvider provider;

        public static IServiceProvider Provider
        {
            get
            {
                if (provider == null)
                {
                    provider = Startup.ConfigureService();
                }

                return provider;
            }
        }
    }
}
