// <auto-generated />
namespace EducationPortalConsoleApp.Helpers
{
    using System;
    using System.Configuration;
    using EducationPortalConsoleApp.DependencyInjection;
    using Microsoft.Extensions.Configuration;

    public static class ProviderServicePL
    {
        private static IServiceProvider provider;

        public static IServiceProvider Provider
        {
            get
            {
                if (provider == null)
                {
                    provider = new Startup().ConfigureService();
                }

                return provider;
            }
        }
    }
}
